<?php

namespace AppBundle\Repository;
use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
    public function nbNoteByUser($userId)
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql="SELECT COUNT(id) FROM commentaire WHERE user_id= :userId GROUP BY :userId";
        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        try {
           $stmt->execute(array('userId' => $userId));
        } catch (DBALException $e) {
        }
        return $stmt->fetchColumn();

    }
    public function sumNoteByUser($userId)
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql="SELECT SUM(note) FROM commentaire WHERE user_id= :userId GROUP BY :userId";
        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        try {
            $stmt->execute(array('userId' => $userId));
        } catch (DBALException $e) {
        }
        return $stmt->fetchColumn();
    }
}
