<?php

namespace AppBundle\Repository;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityRepository;
/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends EntityRepository
{
    public function addParticipant(int $participant, int $groupe)
    {
       /* $sql = "INSERT INTO user_groupe (groupe_id,user_id) VALUES (participant, groupe)";
        $params = array(
            'participant' => $participant,
            'groupe' => $groupe,

        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();*/
        $conn = $this->getEntityManager()->getConnection();
        try {
            $conn->insert('user_groupe', array('user_id' => $participant, 'groupe_id' => $groupe));
        } catch (DBALException $e) {
        }

    }




    public function findGroupeByUserId($userId)
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql="SELECT nom FROM groupe g, user_groupe u WHERE g.id=u.groupe_id AND u.user_id= :userId";
        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        try {
            $stmt->execute(array('userId' => $userId));
        } catch (DBALException $e) {
        }
        $stmt->fetchAll();

    }

    public function delParticipantById($userId,$groupeId)
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql="DELETE FROM user_groupe WHERE user_groupe.groupe_id = :groupeId AND user_groupe.user_id = :userId";
        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        try {
            $stmt->execute(array('groupeId' => $groupeId,'userId' => $userId));
        } catch (DBALException $e) {
        }
        //var_dump($stmt->fetchAll());

    }
}
