<?php

namespace AppBundle\Repository;
use AppBundle\AppBundle;

/**
 * PlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByArrondissement($arr){
        $conn = $this->getEntityManager();
        $qb = $conn->createQueryBuilder();

// this returns an array

        $plats = $qb->select(array('p'))
            ->from('AppBundle:Plat', 'p')
            ->join('AppBundle:Reservation', 'r')
            ->where('p.id = r.plat')
            ->andWhere('r.cp = :arr')
            ->setParameter('arr', $arr)
            ->orderBy('p.creeA', 'ASC')
            ->getQuery()
            ->getResult();
    return $plats;
    }

}
