<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Plat extends \AppBundle\Entity\Plat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'nomPlat', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'categoriePlat', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'descriptionPlat', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'dureeValide', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'creeA', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'prix', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'imagePlat', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'commentaires', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'users', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'userPoste'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'nomPlat', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'categoriePlat', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'descriptionPlat', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'dureeValide', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'creeA', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'prix', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'imagePlat', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'commentaires', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'users', '' . "\0" . 'AppBundle\\Entity\\Plat' . "\0" . 'userPoste'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Plat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUserPoste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPoste', []);

        return parent::getUserPoste();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPoste($userPoste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPoste', [$userPoste]);

        return parent::setUserPoste($userPoste);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagePlat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagePlat', []);

        return parent::getImagePlat();
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaires', []);

        return parent::getCommentaires();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaires($commentaires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaires', [$commentaires]);

        return parent::setCommentaires($commentaires);
    }

    /**
     * {@inheritDoc}
     */
    public function setImagePlat($imagePlat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagePlat', [$imagePlat]);

        return parent::setImagePlat($imagePlat);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPlat($idPlat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPlat', [$idPlat]);

        return parent::setIdPlat($idPlat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPlat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPlat', []);

        return parent::getIdPlat();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPlat($nomPlat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPlat', [$nomPlat]);

        return parent::setNomPlat($nomPlat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPlat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPlat', []);

        return parent::getNomPlat();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoriePlat($categoriePlat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoriePlat', [$categoriePlat]);

        return parent::setCategoriePlat($categoriePlat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriePlat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriePlat', []);

        return parent::getCategoriePlat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionPlat($descriptionPlat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionPlat', [$descriptionPlat]);

        return parent::setDescriptionPlat($descriptionPlat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionPlat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionPlat', []);

        return parent::getDescriptionPlat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeValide($dureeValide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeValide', [$dureeValide]);

        return parent::setDureeValide($dureeValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeValide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeValide', []);

        return parent::getDureeValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreeA($creeA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreeA', [$creeA]);

        return parent::setCreeA($creeA);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreeA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreeA', []);

        return parent::getCreeA();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\AppBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', [$user]);

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\AppBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', [$user]);

        return parent::removeUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommentaire(\AppBundle\Entity\Commentaire $commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommentaire', [$commentaire]);

        return parent::addCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommentaire(\AppBundle\Entity\Commentaire $commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommentaire', [$commentaire]);

        return parent::removeCommentaire($commentaire);
    }

}
